### ISSUE TITLE
Unable to download the CHICO dataset

### ISSUE THREAD

**Issue by OmkarKabadagi5823** [AlessioSam/CHICO-PoseForecasting#1]
I am exploring Human Pose Prediction and I cam across the paper and found it interesting. I was planning to download the data-set to try out the code but the download stops abruptly in between while downloading. I find this issue persistent with other devices.

**Comment by federicocunico** [comment]
Hi
I've tried now to download the skeletons and it went well.
If you want to test the code you probably will need only the skeletons.
The RGBs are present if you are planning to do some HPE over the frames (you will find the camera parameters file aswell). The RGBs frames are a pretty heavy zip file, therefore you will need to have a stable connection. After the download fails, try to press "Retry" on the browser and see if it goes to the end. Maybe there is some issue in Microsoft OneDrive...

**Comment by federicocunico** [comment]
I tried to download it from another connection and I can confirm you that the single files are downloaded fine.
Can you try downloading each file individually?

**Comment by OmkarKabadagi5823** [comment]
Hey @federicocunico . I was finally able to download the 3d skeleton file. it took me a lot of tries. i am not sure if it was my network or the microsoft One drive. Thank you for your quick response.
